name: GitHub Actions Test

on:
    push:
        branches: ["main"]

jobs:
    publicar_imagem_docker:
        runs-on: ubuntu-latest
        steps:
            - name: chackout
              uses: actions/checkout@v4
            - name: build imagem docker
              run: docker build . -t ${{ vars.DOCKER_REPOSITORY }}:latest -t ${{ vars.DOCKER_REPOSITORY }}:${{ github.run_number }}
            - name: login no docker hub
              run: docker login -u ${{ secrets.USER_DOCKER }} -p ${{ secrets.TOKEN_DOCKERHUB }}
            - name: push imagem docker
              run: docker push --all-tags ${{ vars.DOCKER_REPOSITORY }}
# Te