name: GitHub Actions Test

on:
    push:
        branches: ["main"]

jobs:
    publicar_imagem_docker:
        runs-on: ubuntu-latest
        steps:
            - name: chackout
              uses: actions/checkout@v4
            - name: build imagem docker
              run: docker build . -t ${{ vars.DOCKER_REPOSITORY }}:latest -t ${{ vars.DOCKER_REPOSITORY }}:${{ github.run_number }}
            - name: login no docker hub
              run: docker login -u ${{ secrets.USER_DOCKER }} -p ${{ secrets.TOKEN_DOCKERHUB }}
            - name: push imagem docker
              run: docker push --all-tags ${{ vars.DOCKER_REPOSITORY }}

    trivy_test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: build docker
              run: docker build . -t testedocker:${{ github.sha }}
            - name: realizar teste
              uses: aquasecurity/trivy-action@0.26.0
              with:
                  image-ref: 'testedocker:${{ github.sha }}'
                  format: 'table'
                  exit-code: '1'
                  ignore-unfixed: true
                  vuln-type: 'library'
                  severity: 'CRITICAL,HIGH'
